### ISSUE TITLE
[Bug]: Using SDK version 0.14.2+ Still Connects to Rabby if Installed

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-sdk#650] opened 2024-01-26 16:07 UTC
### SDK

Web

### Provide environment information

I'm running ViteJS React web application on Chrome

### MetaMask SDK Version

0.14.3

### MetaMask Mobile app Version

N/A

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

Considering that SDK is now supporting EIP-6963 I assumed this issue would no longer happen. It can happen when a user has other wallets installed that identify as MetaMask (ie. metamask=true) like Rabby wallet.

When I use the Extension to connect instead of mobile, Rabby Wallet is opened along with (and/or) MetaMask, but often MetaMask gets hidden.

### Expected Behavior

I have implemented EIP-6963 in a similar ViteJS application and there is no issues detecting thee wallets individually and connecting to the right wallet when that specific wallet (ie. MetaMask) is selected.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

N/A Just install Rabby and SDK

### To Reproduce

Create a ViteJS application (use SDK-React-UI for simplest repro).
Install Rabby wallet and ensure that MetaMask and Rabby are both enabled.

Connect to MetaMask > Choose Extension > Connect

https://github.com/MetaMask/metamask-sdk/assets/4899480/9bdf6c55-5571-47de-b45a-f6fe409bdd58

**Comment by andreahaku** [comment] 2024-02-05 10:57
@httpJunkie we are looking into it but it's fundamental for us to also know the version of the MM Extension used. Thanks

**Comment by omridan159** [comment] 2024-02-07 08:35
@httpJunkie 

After investigating, it seems the issue you encountered is an expected behavior due to how wallet extensions handle context changes. At 0:54 in your video, the page wasn't refreshed after switching from Rabby to MetaMask, which is necessary because Rabby notifies users through a popup that a refresh is needed for changes to take effect.
If the browser is not refreshed, Rabby's context remains in place.

To resolve this, refresh the page after switching wallets.
For guidance, refer to this video demonstrating the correct process of toggling between MetaMask and Rabby with a page refresh.

Thanks!

https://github.com/MetaMask/metamask-sdk/assets/61094771/52d9d6f2-0547-4dfb-9150-adb285065a8e

**Comment by omridan159** [comment] 2024-02-07 08:37
Answered after investigation here:
https://github.com/MetaMask/metamask-sdk/issues/650

**Comment by omridan159** [comment] 2024-02-27 12:25
Hi @httpJunkie , we’re closing this for now, please feel free to re-open the issue if it still persists

**Closed by omridan159** 2024-02-27 12:25 UTC
Labels: Bug Triage
