### ISSUE TITLE
Unable to connect to the Metamask wallet version react-native 0.68.1.

### ISSUE THREAD

**Issue by Ngoca1k15PT** [MetaMask/metamask-sdk#199] opened 2023-07-10 10:13 UTC
I followed the instructions provided in the documentation, but I am unable to connect to the Metamask wallet. I received the following error message: ' MetaMaskSDK error during initialization [TypeError: undefined is not an object (evaluating '_e48.dappMetadata')] ' . 

version react-native : 0.68.1

**Comment by christopherferreira9** [comment] 2023-07-12 09:35
Hi @Ngoca1k15PT ! 
Can you try to use the [example](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo) dapp to see if the issue persists?

**Comment by Ngoca1k15PT** [comment] 2023-07-13 02:39
Hi @christopherferreira9 , I followed the sample project, but it still doesn't work for React Native version 0.68.1

**Comment by abretonc7s** [comment] 2023-07-26 09:44
Hi @Ngoca1k15PT , could you please provide the source code of how you initialize the sdk?

**Comment by DinhHoangNgoc** [comment] 2023-07-26 11:19
hi @abretonc7s , This is my source code reproducing the issue at: https://github.com/Ngoca1k15PT/ConnectMetamaskSdk.

**Comment by christopherferreira9** [comment] 2023-08-02 09:41
Hi @DinhHoangNgoc , can you try to bump the react-native version you're using? The SDK works best in from version 0.71.0 onwards because of performance issues on cryptographic libraries.

**Comment by christopherferreira9** [comment] 2023-08-31 09:35
Hi @DinhHoangNgoc ! We are going to close this issue, if you encounter any other issues please open a new issue.

**Closed by christopherferreira9** 2023-08-31 09:35 UTC
Labels: Bug Triage

**Comment by cgrewon** [comment] 2024-02-15 15:57
I have tested with latest metamask mobile app (7.14.0) and     "react-native": "0.73.4", "@metamask/sdk-react": "^0.14.2",  "ethers": "^5.7.2",  "eciesjs": "^0.4.6",
But app does not open connect popup at all.
COMM_SERVER_URL='https://metamask-sdk-socket.metafi.codefi.network/'
INFURA_API_KEY='6c.....'
These are what I used for infura api key and initialSocketServer url, 
Please help me.

**Comment by gusoliveira21** [comment] 2025-01-11 00:40
@cgrewon Did you find a solution?
