### ISSUE TITLE
Broken onboarding 

### ISSUE THREAD

**Issue by pociej** [MetaMask/metamask-sdk#360] opened 2023-09-20 20:02 UTC
SDK just because provider component is added to components tree immediatelly sends JSONRpc request for accounts. 
There is no option in `MetaMaskSDKOptions` to prevent this behaviour.  
Installation check can be prevented by `  checkInstallationImmediately: false` but accounts check no matter what which makes SDK unusable in some cases. 

There is also another problem that after using SDK I render user installation widget, during installation metamask reloads page without my control.

**Comment by abretonc7s** [comment] 2023-09-21 04:09
It seems that somewhere in your code you are calling eth_requestAccounts which may be from one of your library or package.
When using `checkInstallationImmediately` the provider will not make any query automatically.

**Comment by pociej** [comment] 2023-09-21 05:45
@abretonc7s thx for reply I will check this and eventually provide reproduction example. 
However more important problem is second one. Maybe I should move it to separated issues. 
Being forced to refresh the page produces bad UX. This is something to do with metamask browser plugin itself 
but I wonder what i the reason of such behaviour and is there a way to skip it.

**Comment by abretonc7s** [comment] 2023-09-23 05:12
Have you tried any of the provided examples? The sdk itself doesn't create any page reload.

**Comment by christopherferreira9** [comment] 2023-09-26 08:39
Hi @pociej , have you managed to try one of our [examples](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples)?

**Comment by pociej** [comment] 2023-10-05 12:46
@christopherferreira9 why this is closed? I saw examples but it doesnt solve the problem. This behaviour is still here and it is out of control.

**Comment by christopherferreira9** [comment] 2023-10-05 13:07
The issue was closed because there was no activity for 2 weeks. I'm reopening the issue. 
Are you able to share a repo where the issue is reproducible?

**Comment by christopherferreira9** [comment] 2023-10-11 09:50
Hi @pociej . Can you please share a repo where the issue is reproducible? Also, can you try to isolate the usage of the SDK to understand if the issue lays there?

**Comment by christopherferreira9** [comment] 2023-10-19 09:39
Hi @pociej ! We will be closing this issue since there hasn't been any feedback on it. Please feel free to open a new issue and in the meantime please check the [examples](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples) folder we have in our repo.

**Closed by christopherferreira9** 2023-10-19 09:39 UTC
Labels: Bug Triage
