### ISSUE TITLE
Stuck on ios MetaMask App [Bug]: 

### ISSUE THREAD

**Issue by YusufBesim** [MetaMask/metamask-sdk#480] opened 2023-11-07 20:58 UTC
### SDK

Unity

### Provide environment information

Using M1 Max Macbook Pro Slicon, Unity version is 2022.3.11f1.
Blank URP Project.

### MetaMask SDK Version

1.2.1

### MetaMask Mobile app Version

7.9.0

### How are you deploying your application? (if relevant)

iOS

### Describe the Bug

Hello,

When push start button i have this two error;

MetaMask: MetaMaskUnity initialization failed
UnityEngine.Logger:LogError (string,object)
MetaMask.Logging.MetaMaskUnityLogger:LogError (object) (at Assets/MetaMask/Scripts/Logging/MetaMaskUnityLogger.cs:62)
MetaMask.Logging.MetaMaskDebug:LogError (object) (at Assets/MetaMask/Runtime/Logging/MetaMaskDebug.cs:41)
MetaMask.Unity.MetaMaskUnity:Initialize (MetaMask.Unity.MetaMaskConfig,MetaMask.Transports.IMetaMaskTransport,MetaMask.Sockets.IMetaMaskSocketWrapper) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:316)
MetaMask.Unity.MetaMaskUnity:Initialize (MetaMask.Unity.MetaMaskConfig) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:204)
MetaMask.Unity.MetaMaskUnity:Awake () (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:171)

ArgumentException: The context string 2a7bcc01-d10c-40c0-9f36-98fd646f0944 is attempting to create a new EventDelegator that overlaps with an existing EventDelegator
EventEmitter.NET.EventDelegator..ctor (System.String contextString) (at Assets/MetaMask/Plugins/Libraries/EventEmitter.NET/Runtime/EventDelegator.cs:55)
MetaMask.MetaMaskWallet..ctor (MetaMask.MetaMaskDataManager dataManager, MetaMask.IAppConfig appConfig, System.String sessionId, MetaMask.Cryptography.IEciesProvider eciesProvider, MetaMask.Transports.IMetaMaskTransport transport, MetaMask.Sockets.IMetaMaskSocketWrapper socket, System.String socketUrl) (at Assets/MetaMask/Runtime/MetaMaskWallet.cs:316)
MetaMask.Unity.MetaMaskUnity.Initialize (MetaMask.Unity.MetaMaskConfig config, MetaMask.Transports.IMetaMaskTransport transport, MetaMask.Sockets.IMetaMaskSocketWrapper socket) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:262)
UnityEngine.Logger:LogException(Exception)
MetaMask.Logging.MetaMaskUnityLogger:LogException(Exception) (at Assets/MetaMask/Scripts/Logging/MetaMaskUnityLogger.cs:69)
MetaMask.Logging.MetaMaskDebug:LogException(Exception) (at Assets/MetaMask/Runtime/Logging/MetaMaskDebug.cs:50)
MetaMask.Unity.MetaMaskUnity:Initialize(MetaMaskConfig, IMetaMaskTransport, IMetaMaskSocketWrapper) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:317)
MetaMask.Unity.MetaMaskUnity:Initialize(MetaMaskConfig) (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:204)
MetaMask.Unity.MetaMaskUnity:Awake() (at Assets/MetaMask/Scripts/MetaMaskUnity.cs:171)

### Expected Behavior

init successfully and communicate with metamask

### To Reproduce

Nothing special. I installed plugin from asset store. Then gone to sample scene and hit play.

**Comment by YusufBesim** [comment] 2023-11-07 21:09
Hello, 
There is update. I changed RPC with infura. Now it works.

But when scan QR code MetaMask APP stucking. Screen video below.

https://github.com/MetaMask/metamask-sdk/assets/1141927/1f4de2f1-cb33-4fcd-8315-7e05ae42f842

**Comment by christopherferreira9** [comment] 2023-11-08 15:08
Hi @YusufBesim ! 
The root cause for the connection loop was related to the app icon being too big. Can you please try to delete the icon or use a smaller one?
Also, we're about to release a new version of the Unity SDK (v1.2.2) where this should be fixed. Can you please try with the new version? This icon is located in `Assets/MetaMask/Resources/MetaMask/Config/Default` .

**Comment by christopherferreira9** [comment] 2023-11-16 15:24
Hi @YusufBesim ! We're going to close this issue assuming it was solved. Please feel free to open a new one if the issue still persists.

**Closed by christopherferreira9** 2023-11-16 15:24 UTC
Labels: Bug Triage Unity
