### ISSUE TITLE
When adding custom network metamask crashed.

### ISSUE THREAD

**Issue by swatijindal12** [MetaMask/metamask-sdk#477] opened 2023-11-07 12:48 UTC
## Code sample

i am using this code 

 try {
      console.log("hello2");
      await ethereum.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: '0x483' }],
      });
    } catch (switchError) {
      console.log("hello3");
      // This error code indicates that the chain has not been added to MetaMask.
      if (switchError.code === 4902) {
        try {
          console.log("hello4");
          await ethereum.request({
            method: 'wallet_addEthereumChain',
            params: [
              {
                chainId: '0x483',
                chainName: 'Quorum',
                rpcUrls: ['https://...........'] ,
              },
            ],
          });
        } catch (addError) {
          // handle "add" error
        }
      }
      // handle other "switch" errors
    }
    
    When i am adding custome network in mobile app. Metamask app crashed.

**Comment by A-Feder** [comment] 2023-11-14 09:37
Duplicate of #476

**Closed by A-Feder** 2023-11-14 09:37 UTC
