### ISSUE TITLE
[Bug]: Is the Electron SDK example too old?

### ISSUE THREAD

**Issue by D7x7z49** [MetaMask/metamask-sdk#804] opened 2024-04-13 04:59 UTC
### SDK

Node.js

### Provide environment information

Because following the instructions in `packages/examples/electronjs/README.md` led to errors and was not executable, I created a separate project on my own.

- Window 10
- Visual Studio Code
- electron + vite + react
- `yarn create @quick-start/electron test-dev  --template react-ts`

### MetaMask SDK Version

"@metamask/sdk": "^0.18.3"

### Describe the Bug

I encountered a TypeScript type error 'Missing return type on function' while following the instructions on the official website in `packages/examples/electronjs`. I apologize as I am a beginner, and I am exploring the possibilities of Electron and MetaMask on the internet. The error snippet is as shown in the screenshot below.

1.  ![image](https://github.com/MetaMask/metamask-sdk/assets/85430783/3ea8122d-d73b-49f5-afc2-10966abb6194)
2.  ![image](https://github.com/MetaMask/metamask-sdk/assets/85430783/552915ad-eb56-4865-a160-fc1fb9745e1a)

The above is just a personal issue I encountered. The project itself has some outdated dependencies, causing abnormalities during yarn installation.

### Expected Behavior

1. 
![image](https://github.com/MetaMask/metamask-sdk/assets/85430783/f1c8d208-cb1e-4453-a18e-e3deec0b64e2)
2. 
![image](https://github.com/MetaMask/metamask-sdk/assets/85430783/38ff1d18-c8a2-4226-a262-6e5a7d1e584e)

I want to know how to deal with this problem. There is too little information online, so I can only turn to you for help.

### To Reproduce

The Electron SDK example itself has issues, as following the steps in `packages/examples/electronjs/README.md` leads to abnormal errors. What I need to understand is the solution to the `Missing return type on function.` error in the context of using the combination of electron + vite + react + TS. Of course, I am a newbie.

**Comment by D7x7z49** [comment] 2024-04-13 05:04
About old ?

```txt
PS \metamask-sdk\packages\examples\electronjs> yarn install
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @metamask/sdk@npm:0.17.2 [20036] provides cross-fetch (p5162f) with version 4.0.0, which doesn't satisfy what @metamask/sdk-communication-layer requests
➤ YN0002: │ @metamask/sdk@npm:0.17.2 [20036] doesn't provide react-i18next (p0b1c4), requested by @metamask/sdk-install-modal-web
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter 
p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-parser@npm:18.1.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yauzl@npm:2.10.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 54ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 18s 34ms
➤ YN0000: Done with warnings in 19s 830ms
PS \metamask-sdk\packages\examples\electronjs>
```

**Comment by christopherferreira9** [comment] 2024-04-16 21:14
Hi @D7x7z49 ! We're currently updating our examples. Do you see the those same errors when opening the project directly or only on the project you were trying to setup?
The log you shared of the `yarn install` command looks normal :)

**Comment by abretonc7s** [comment] 2024-04-22 09:25
Hi @D7x7z49 , the issue is from your linter configuration.
I am closing for now since it is not sdk related, as the message suggest you can add the return type to the function.

**Closed by abretonc7s** 2024-04-22 09:25 UTC
Labels: Bug Triage

**Comment by D7x7z49** [comment] 2024-04-22 09:34
ok
